config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :journals do
    resources :entries
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  default_scope { order(date: :desc) }

  belongs_to :user
  belongs_to :journal

  validates :date, presence: true, uniqueness: { scope: :journal_id }
  validates :thoughts, presence: true, length: { minimum: 10}

  broadcasts_to ->(entry) { [entry.journal, :entries] }, inserts_by: :prepend
end

app/models/journal.rb
# frozen_string_literal: true

class Journal < ApplicationRecord
  default_scope { order(updated_at: :desc) }
  before_save { |journal| journal.title = journal.title.titleize }
  belongs_to :user
  has_many :entries, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :user_id }

  broadcasts_to ->(journal) { [journal.user, :journals] }, inserts_by: :prepend
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { |user| user.name = user.name.titleize }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy
  has_many :journals, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# All other controllers inherit from this controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

# All actions regarding the entry object lives here.
class EntriesController < ApplicationController
  before_action :set_journal
  before_action :set_entry, only: %i[edit update destroy]

  def index; end

  def new
    @entry = @journal.entries.new
  end

  def create
    @entry = @journal.entries.build(entry_params)
    @entry.user = current_user
    if @entry.save
      respond_to do |format|
        format.html { redirect_to @journal, notice: 'Your entry has been created successfully' }
        format.turbo_stream { flash.now[:notice] = 'Your entry has been created successfully' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    return unless @entry.update(entry_params)

    respond_to do |format|
      format.html { redirect_to @journal, notice: 'Your entry has been updated successfully' }
      format.turbo_stream { flash.now[:notice] = 'Your entry has been updated successfully' }
    end
  end

  def destroy
    return unless @entry.destroy

    respond_to do |format|
      format.html { redirect_to @journal, notice: 'Your entry has been deleted successfully' }
      format.turbo_stream { flash.now[:notice] = 'Your entry has been deleted successfully' }
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:thoughts, :date)
  end

  def set_journal
    @journal ||= Journal.find(params[:journal_id])
  end

  def set_entry
    @entry ||= Entry.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# This is the controller class in charge of the landing page after successfull sign in.
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @user_journals = current_user.journals
    @journal = Journal.new
  end
end

app/controllers/journals_controller.rb
# frozen_string_literal: true

# Journals Controller actions are defined here
class JournalsController < ApplicationController
  before_action :set_journal, except: [:new]

  def new
    @journal = Journal.new
  end

  def create
    @journal = current_user.journals.build(journal_params)
    if @journal.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Journal was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Journal was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @journal = Journal.find_by(id: params[:id])
  end

  def show
    @journal = Journal.find_by(id: params[:id])
    @journal_entries = @journal.entries
    @entry = @journal.entries.new
  end

  def update
    return unless @journal.update(journal_params)

    respond_to do |format|
      format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
      format.turbo_stream { flash.now[:notice] = 'Journal was successfully updated.' }
    end
  end

  def destroy
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Journal was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Journal was successfully destroyed.' }
    end
  end

  private

  def set_journal
    @journal = Journal.find_by(id: params[:id])
  end

  def journal_params
    params.require(:journal).permit(:title, :is_private)
  end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true

# This controller inherits from Application controller so it can have acess to the app stack.
class TurboDeviseController < ApplicationController
  # controller is used to ensure devise works well with Rails turbo
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash_messages'
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/entries/_entry.html.haml
= turbo_frame_tag dom_id(entry) do 
  - if entry.date 
    .entry-div.card-it.mb-7
      .italic.flex.flex-wrap.justify-between.p-2.bg-neutral-400.text-white
        %p= entry.date.strftime('%B %d, %Y') 
        %div.flex
          .rounded.border.bg-blue-400.px-3.py-1.text-xs.mx-2
            = link_to 'Edit', [:edit, @journal, entry], data: { turbo_frame: dom_id(entry) }
          .rounded.border.bg-red-400.px-3.py-1.text-xs
            = link_to 'Delete', [@journal, entry], data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
      .max-w-xl.ml-mr-auto.bg-blue-200.p-3.text-justify= simple_format entry.thoughts

app/views/entries/_form.html.haml
= form_with model: [@journal, entry] do |f| 
  .form-group.mb-6.max-w-l
    .flex.flex-wrap.max-w-m.text-sm.text-slate-500.mb-4
      = f.label :date, 'Entry date:', class: 'mr-4'
      = f.date_field :date
    - if entry.errors.include?(:date)
      - entry.errors.full_messages_for(:date).each do |error_message|
        .text-xs.text-center.text-red-700= error_message
    = f.rich_text_area :thoughts, placeholder: 'Remember to select a date for this!', class: "my-4 placeholder:italic placeholder:text-slate-400 form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
    - if entry.errors.include?(:thoughts)
      - entry.errors.full_messages_for(:thoughts).each do |error_message|
        .text-xs.text-center.text-red-700= error_message
    = f.submit "#{object_action} ENTRY", class: "px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    = link_to "CANCEL", @journal, class: "px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"

app/views/entries/create.turbo_stream.haml
= turbo_stream.prepend 'entries', @entry
= turbo_stream.update Entry.new, ''
= render_turbo_stream_flash_messages

app/views/entries/destroy.turbo_stream.haml
= turbo_stream.remove @entry
= render_turbo_stream_flash_messages

app/views/entries/edit.html.haml
= turbo_frame_tag dom_id(@entry) do
  = render 'entries/form', entry: @entry, object_action: 'UPDATE'

app/views/entries/new.html.haml
= turbo_frame_tag dom_id(@entry) do
  = render 'entries/form', entry: @entry, object_action: 'CREATE'

app/views/entries/update.turbo_stream.haml
= turbo_stream.update @entry
= render_turbo_stream_flash_messages

app/views/home/index.html.haml
.text-center.justify-content-center.container
  %h1 Welcome #{current_user.name}, to your Memories Dashboard
  %p Below are your saved memories arranged by folder.

  .header
    %p.font-bold My Journals
    = link_to "New Journal", new_journal_path, class: "px-3 py-2 bg-green-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:bg-green-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-800 active:shadow-lg transition duration-150 ease-in-out", data: {turbo_frame: dom_id(@journal)}

  = turbo_frame_tag dom_id(@journal)

  = turbo_stream_from current_user, :journals
  .journal-list
    %ul#journals
      = render @user_journals

app/views/journals/_form.html.haml
= form_for journal do |f|
  .form-group.mb-6.max-w-l
    = f.label "Title", class: "form-label inline-block mb-2 text-gray-700"
    = f.text_field :title, class: "form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
    - if journal.errors.include?(:title)
      - journal.errors.full_messages_for(:title).each do |error_message|
        .text-xs.text-center.text-red-700= error_message
    %br/
    = button_tag "#{object_action} JOURNAL", class: "px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    = link_to "CANCEL", root_path, class: "px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"

app/views/journals/_journal.html.haml
= turbo_frame_tag dom_id(journal) do
  .flex.flex-wrap.justify-between.card-it.block.p-6.mb-6.max-w-l
    = link_to journal.title, journal, data: { turbo_frame: '_top' } ,class: "hover:underline text-gray-700 dark:text-gray-400"
    %div.flex.flex-wrap
      .rounded.border.bg-neutral-400.px-3.py-1.text-xs
        = link_to 'Edit', edit_journal_path(journal), data: { turbo_frame: dom_id(journal) }
      .rounded.border.bg-red-400.px-3.py-1.text-xs
        = link_to 'Delete', journal, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/journals/create.turbo_stream.haml
= turbo_stream.update Journal.new, ""
= render_turbo_stream_flash_messages

app/views/journals/destroy.turbo_stream.haml
= turbo_stream.remove @journal
= render_turbo_stream_flash_messages

app/views/journals/edit.html.haml
= turbo_frame_tag dom_id(@journal) do
  = render 'form', journal: @journal, object_action: "UPDATE"

app/views/journals/new.html.haml
= turbo_frame_tag dom_id(@journal) do
  = render 'form', journal: @journal, object_action: "CREATE"

app/views/journals/show.html.haml
.text-center.container
  %p.font-bold= @journal.title
  .header
    %p.font-bold 
      = link_to sanitize("&larr; Back to Journals"), root_path
    = link_to 'New Entry', new_journal_entry_path(@journal), data: { turbo_frame: dom_id(@entry)}, class: "px-3 py-2 bg-green-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:bg-green-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-800 active:shadow-lg transition duration-150 ease-in-out"
  = turbo_frame_tag dom_id(@entry)

  = turbo_stream_from @journal, :entries
  .entry-list
    %ul#entries
      = render @journal_entries

app/views/journals/update.turbo_stream.haml
= turbo_stream.update @journal
= render_turbo_stream_flash_messages

app/views/layouts/_flash_messages.html.haml
- flash.each do |flash_type, message|
  .flash_message{"data-action" => "animationend->flash-removals#remove", "data-controller" => "flash-removals"}
    = message

app/views/layouts/_footer.html.haml
%footer.text-sm.text-center.bg-gray-100.text-gray-600.bottom-0.w-full
  .flex.justify-center.items-center.lg:justify-between.px-3.py-2.border-b.border-gray-300
    .mr-12.hidden.lg:block
      %span You can connect with me here on any of these platforms:
    .flex.justify-center
      %a.mr-6.text-blue-700{href: "https://www.facebook.com/erchiboy"}
        %svg{"aria-hidden" => "true", class: "w-2.5", "data-icon" => "facebook-f", "data-prefix" => "fab", focusable: "false", role: "img", viewbox: "0 0 320 512", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z", fill: "currentColor"}
      %a.mr-6.text-blue-400{href: "https://www.twitter.com/iam_chibuzor"}
        %svg.w-4{"aria-hidden" => "true", "data-icon" => "twitter", "data-prefix" => "fab", focusable: "false", role: "img", viewbox: "0 0 512 512", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z", fill: "currentColor"}
      %a.mr-6.text-red-600{href: "mailto:cefedigbuej@gmail.com"}
        %svg{"aria-hidden" => "true", class: "w-3.5", "data-icon" => "google", "data-prefix" => "fab", focusable: "false", role: "img", viewbox: "0 0 488 512", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z", fill: "currentColor"}
      %a.mr-6.text-purple-900{href: "https://www.linkedin.com/in/uzorchibuzor"}
        %svg{"aria-hidden" => "true", class: "w-3.5", "data-icon" => "linkedin-in", "data-prefix" => "fab", focusable: "false", role: "img", viewbox: "0 0 448 512", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z", fill: "currentColor"}
      %a.text-black{href: "https://github.com/uzorjchibuzor"}
        %svg.w-4{"aria-hidden" => "true", "data-icon" => "github", "data-prefix" => "fab", focusable: "false", role: "img", viewbox: "0 0 496 512", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z", fill: "currentColor"}
  .text-center.p-2.bg-gray-200
    %span 
      \&copy; #{Time.now.year}
      = link_to "#{ENV['APP_NAME']}", root_path, class: "hover:underline font-bold"

    %p 
      This application is designed with Ruby on Rails by 
      %a.italic.text-blue-900.hover:underline{href: 'https://uzorjchibuzor.netlify.app'} Chibuzor Efedigbue
    %p
      Ruby #{ENV['RBENV_VERSION']} | Rails #{Rails.version} | Env #{Rails.env}

app/views/layouts/_header.html.haml
%nav.border-b.py-6
  .container  
    .flex.flex-wrap.justify-between.items-center
      .flex.items-center
        .mx-5.text-3xl.font-bold
          = link_to 'Memories', root_path
        %ul.flex.items-center.flex-col.md:flex-row.md:space-x-5.w-full
      .flex.items-center.gap-2
        - if user_signed_in?
          .btn-primary= button_to "Logout", destroy_user_session_path, :method => 'delete', class: "px-3 py-2 bg-red-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"
        - else
          = link_to 'Login', new_user_session_path, class: "px-3 py-2 bg-green-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:bg-green-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-800 active:shadow-lg transition duration-150 ease-in-out"
          = link_to 'Sign Up', new_user_registration_path, class: "px-3 py-2 bg-blue-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Memories
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = hotwire_livereload_tags if Rails.env.development?
    = stylesheet_link_tag "trix.css"
    = javascript_include_tag "trix"
  %body 
    .flex.flex-col.bg-gradient-to-b.from-blue-200.to-green-200.hack-height
      = render "layouts/header"
      %div.container
        #flash.flash
          = render "layouts/flash_messages"
        = yield
    = render "layouts/footer"